<a href="https://colab.research.google.com/github/Imen1028/Authentication-Secrets/blob/master/00_tensorflow_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# In this notebook, we are going to cover some of the most fundamental concepts of tensors using TensorFlow.

More specifically, we're going to cover:
* Introduction to tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & Numpy
* Using @tf.function (a way to speed up your regular Python function)
* Using GPUs with TensorFlow (or TPUs)
* Exercises to try for yourself!

## Introduction to Tensors

In [ ]:
# Import TensorFlow
import tensorflow as tf
print(tf.__version__)

2.15.0


In [ ]:
# Create tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# Check the number of dimensions of a tensor (ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
# Create a vector
vector = tf.constant([10, 10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
# Check the dimension of our vector
vector.ndim

1

In [ ]:
# Create a martix (has more than one dimension)
matrix = tf.constant([[10, 7], [7, 10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
# Create another matrix
another_matrix = tf.constant([[10.,7.],
                              [3., 2.],
                              [5., 8.]], dtype=tf.float16) # specify the data type with dtype parameter.

another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 5.,  8.]], dtype=float16)>

In [ ]:
# What's the number dimensions of another_matrix?
another_matrix.ndim

2

In [ ]:
# Let's create a tensor
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                       [[7, 8, 9],
                       [10, 11, 12]],
                       [[13, 14, 15],
                       [16, 17, 18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

What we've created so far:
* Scalar: a single number
* Vector: a number with diretion (e.g. wind speed and direction)
* Matrix: a 2-dimensional array of numbers
* tensor: an n-dimensional array of numbers (when n can be any number, a 0-dimensional tensor is a scalar, a 1-dimensional tensor is a vector)

# Create the same tensor with tf.Variable()


In [ ]:
# Create the same tensor with tf.Variable() as above
changeable_tensor = tf.Variable([10, 7])
unchangeable_tensor = tf.constant([10, 7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
# Let's try change one of the elements in our changeable tensor
# changeable_tensor[0] = 12
# changeable_tensor
# it returns an error "'ResourceVariable' object does not support item assignment"

In [ ]:
# How about we try assign()
changeable_tensor[0].assign(7)
changeable_tensor
# We successfully changed the value in the tensor
# btw, it's really important to read the doc, it has many useful info

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
# unchangeable_tensor[0].assign(7)
# it doesn't work cuz it's not mutable

#Creating ramdon tensors

**tf.random.Generator()** is the most commonly used way to generate random values because of its **reproducibility** and **statefulness**.
It relies on its own seed not a global seed, which makes it more reproducibile than other methods.


In [ ]:
# Create two random (but the same) tensors
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=[2,3])
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=[2,3])
print(random_1, random_2)
# random.normal outputs random values from a normal distribution
# random.uniform outputs random values from a uniform distribution
random_3 = tf.random.Generator.from_seed(42)
print(random_3.uniform(shape=[2,3]))

tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]], shape=(2, 3), dtype=float32) tf.Tensor(
[[-0.7565803  -0.06854702  0.07595026]
 [-1.2573844  -0.23193765 -1.8107855 ]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0.7493447  0.73561966 0.45230794]
 [0.49039817 0.1889317  0.52027524]], shape=(2, 3), dtype=float32)


## uniform distribution "tf.random.uniform()"

In [ ]:
random_uni = tf.random.uniform(shape=[2,2], maxval = 3, minval = -2)
random_uni

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[ 1.4394562 ,  0.42239428],
       [ 2.654972  , -0.73906493]], dtype=float32)>


normal distribution "tf.random.normal()"
---



In [ ]:
random_nor = tf.random.normal(shape= [2,2])
random_nor

<tf.Tensor: shape=(2, 2), dtype=float32, numpy=
array([[-0.5590974, -0.5347214],
       [ 2.3730333, -1.5725931]], dtype=float32)>

###Shuffle the order of elements in a tensor


In [ ]:
# Shuffle a tensor (valuable for when you want to shuffle your data so the inherent order doesn't affect the learning)
not_shuffled = tf.constant([[10, 7],
                           [3,4],
                           [2,5]])
# Shuffle our non-shuffled tensor
tf.random.shuffle(not_shuffled, seed = 42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

⛏ **Exercise:** Read through TensorFLow documentation on random seed generation: https://www.tensorflow.org/api_docs/python/tf/random/set_seed and practice writing 5 random tensors and shuffle them.

> Rule 4: "If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence."

###Why Different Numbers are Generated
####Sequential State Updates:
After generating a batch of random numbers, the internal state of the RNG is updated. This means the next batch of random numbers will be different from the first, as the generator's state has changed. This behavior ensures that you get a sequence of different random numbers across calls, which is generally desired in applications requiring random numbers.

####Reproducibility vs. Uniqueness:
The purpose of seeding is not to produce the same number repeatedly but to ensure that the entire sequence of generated numbers is reproducible across runs. If you restart the program and use the same seed, you will get the same sequence of random numbers in the same order.

In [ ]:
rng = tf.random.Generator.from_seed(42)
random_uni_1 = rng.uniform(shape=[3,2])
random_uni_2 = rng.uniform(shape=[3,2])
random_uni_3 = rng.uniform(shape=[3,2])
random_uni_4 = rng.uniform(shape=[3,2])
random_uni_5 = rng.uniform(shape=[3,2])

In [ ]:
print(random_uni_1)
print(random_uni_2)
print(random_uni_3)
print(random_uni_4)
print(random_uni_5)

tf.Tensor(
[[0.7493447  0.73561966]
 [0.45230794 0.49039817]
 [0.1889317  0.52027524]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.7647915  0.03845465]
 [0.8506975  0.20781887]
 [0.711869   0.8843919 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.33853185 0.33070397]
 [0.9244     0.9586116 ]
 [0.8871614  0.6129334 ]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.6006218  0.91749775]
 [0.55770075 0.5953661 ]
 [0.05641675 0.02076614]], shape=(3, 2), dtype=float32)
tf.Tensor(
[[0.67937434 0.5157412 ]
 [0.37234235 0.6137483 ]
 [0.9930316  0.89470756]], shape=(3, 2), dtype=float32)


In [ ]:
# If both the global and the operation seed are set: Both seeds are used in conjunction to determine the random sequence.

tf.random.set_seed(42) # global level random seed
tf.random.shuffle(random_uni_1, seed = 42) # operation level random seed

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0.7493447 , 0.73561966],
       [0.45230794, 0.49039817],
       [0.1889317 , 0.52027524]], dtype=float32)>

### Other ways to make tensors

In [ ]:
# Create a tensor of all ones
tf.ones([10, 7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# Create a tensor of all zeroes
tf.zeros(shape=(3, 4))

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

### Turn NumPy arrays into tensors

The main difference between NumPy arrays and TensorFlow tensors is that tensors can be run on a GPU (much faster for numerical computing)

In [ ]:
# You can also turn NumPy arrays into tensors
import numpy as np
numpy_A = np.arange(1, 25, dtype=np.int32) # create a NumPy array between 1 and 25

# X = tf.constant(some_matrix) # capital for matrix or tensor
# y = tf.constant(vector) # non-capital for vector

a = tf.constant(numpy_A, shape=(2, 3, 4)) # The multiplication of all numbers in shape must be equal to the number of elements in the numpy array
b = tf.constant(numpy_A, shape=(4, 6))
a, b

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(4, 6), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]], dtype=int32)>)

### Getting infomation from our tensors

When dealing with tensors you probably want to be aware of the following attributes:
* Shape
* Rank
* Axis or dimension
* Size

In [ ]:
# Create a rank 4 tensor (4 dimensions)
rank_4_tensor = tf.zeros(shape= [2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor),

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Total element in the tensor
2 * 3 * 4 * 5

120

In [ ]:
rank_4_tensor[0],rank_4_tensor[0][0],rank_4_tensor[0][0][0],rank_4_tensor[0][0][0][0]

(<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
 array([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],
 
        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]], dtype=float32)>,
 <tf.Tensor: shape=(4, 5), dtype=float32, numpy=
 array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=float32)>,
 <tf.Tensor: shape=(5,), dtype=float32, numpy=array([0., 0., 0., 0., 0.], dtype=float32)>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0>)

In [ ]:
# Get various attributes of our tensor
print("Datatype of every element:", rank_4_tensor.dtype)
print("Number of dimensions (rank):", rank_4_tensor.ndim)
print("Shape of tensor:", rank_4_tensor.shape)
print("Elements along the 0 axis:", rank_4_tensor.shape[0])
print("Elements along the last axis:", rank_4_tensor.shape[-1])
print("Total number of elements in our tensor:", tf.size(rank_4_tensor))
print("Total number of elements in our tensor:", tf.size(rank_4_tensor).numpy())

Datatype of every element: <dtype: 'float32'>
Number of dimensions (rank): 4
Shape of tensor: (2, 3, 4, 5)
Elements along the 0 axis: 2
Elements along the last axis: 5
Total number of elements in our tensor: tf.Tensor(120, shape=(), dtype=int32)
Total number of elements in our tensor: 120


### Indexing tensors
Tensors can be indexed just like Python lists.

In [ ]:
# Get the first 2 elements of each dimension

rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [ ]:
# Get the first element form each dimensiom from each index except for the final one.
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_2_tensor = tf.zeros([2, 3], tf.int32)
rank_2_tensor

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[0, 0, 0],
       [0, 0, 0]], dtype=int32)>

In [ ]:
# Get the last item of each of row of our rank 2 tensor
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([0, 0], dtype=int32)>

In [ ]:
# Add in extra dimension to our rank 2 tensor
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]]], dtype=int32)>

In [ ]:
# Alternative to tf.newaxis
tf.expand_dims(rank_2_tensor, axis= -1) # "-1" means expend the final axis

<tf.Tensor: shape=(2, 3, 1), dtype=int32, numpy=
array([[[0],
        [0],
        [0]],

       [[0],
        [0],
        [0]]], dtype=int32)>

In [ ]:
# Expand the 0-axis
tf.expand_dims(rank_2_tensor, axis=0) # expand the 0-axis

<tf.Tensor: shape=(1, 2, 3), dtype=int32, numpy=
array([[[0, 0, 0],
        [0, 0, 0]]], dtype=int32)>

### Manipulating tensors (tensor operations)
**Basic operations**

`+`, `-`, `*`, `/`

In [ ]:
# You can add values to a tensor using the addition operator
tensor = tf.constant([[10,7], [3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
# Original tensor is unchanged
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# Multiplication also works
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [ ]:
# We can use the tensorflow built-in function
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### It is faster to run on GPU is we use the TensorFlow built-in function for multipulation
###e.g.
tf.add(tensor, number)

tf.multiply(tensor, number)

Doc:
https://www.tensorflow.org/api_docs/python/tf/math

In [ ]:
tensor_add = tf.zeros([2,3,4], tf.int32)
tf.add(tensor_add, 10)

<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
array([[[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]],

       [[10, 10, 10, 10],
        [10, 10, 10, 10],
        [10, 10, 10, 10]]], dtype=int32)>

###**Matrix multiplication**
In machine learning, matrix multiplication is one of the most common tensor operations

In [ ]:
# Matrix multiplication in tensorflow
print(tensor)
tf.matmul(tensor, tensor)

tf.Tensor(
[[10  7]
 [ 3  4]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [ ]:
# numbers of columns of the 1st matrix must equal to the number of rows of the 2nd matrix
# 3*3 matrix * 3*2 matrix
tensor_1 = tf.constant([[1,2,5],
                        [7,2,1],
                        [3,3,3]])
tensor_2 = tf.constant([[3,5],
                        [6,7],
                        [1,8]])
# Matrix multiplication
tf.matmul(tensor_1, tensor_2)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [ ]:
# Matrix reshape
x = tf.constant([[1,2,3], [4, 5,6]])
y = tf.constant([[10,7, 10], [4,6, 1]])
x, y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7, 10],
        [ 4,  6,  1]], dtype=int32)>)

In [ ]:
# tf.matmul(x,y)
# we got the error because the shape of these two matrices do not match (2 x 3 * 2 x 2)
# we can solve this problem by reshape either one of the tensor
tf.reshape(y, [3, 2])
tf.matmul(x, tf.reshape(y, [3,2]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 48,  18],
       [126,  54]], dtype=int32)>

In [ ]:
# we can also use tf.transpose() to reshape the tensor
tf.transpose(y), tf.reshape(y, [3,2])
# Notice that the results of tf.transpose and tf.reshape are different
# Becaue tf.transpose() shifts the tensor by the axis
# While tf.reshape() reshapes the tensor according to the shape we type in


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  4],
        [ 7,  6],
        [10,  1]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  7],
        [10,  4],
        [ 6,  1]], dtype=int32)>)

***The dot product***
Matrix multiplication is also referred to as the dot product.
You can perform matrix multiplication using:
* `tf.malmul()`
* `tf.tensordot()`

In [ ]:
x, y

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  7, 10],
        [ 4,  6,  1]], dtype=int32)>)

In [ ]:
# Perform the dot product on x and y (required x or y to be transposed)
tf.tensordot(tf.transpose(x), y, axes = 1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[26, 31, 14],
       [40, 44, 25],
       [54, 57, 36]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y (transposed)
tf.matmul(x, tf.transpose(y))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 54,  19],
       [135,  52]], dtype=int32)>

In [ ]:
# Perform matrix multiplication between x and y (reshaped)
tf.matmul(x, tf.reshape(y, [3, 2]))

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 48,  18],
       [126,  54]], dtype=int32)>

In [ ]:
# Check the values of y, reshape y and transposed y
print(f"Normal: {y}")
print(f"y reshaped to (3,2): {tf.reshape(y, [3,2])}")
print(f"y transposed: {tf.transpose(y)}")

Normal: [[10  7 10]
 [ 4  6  1]]
y reshaped to (3,2): [[10  7]
 [10  4]
 [ 6  1]]
y transposed: [[10  4]
 [ 7  6]
 [10  1]]


### Generally, when performing matrix multiplication on two tensors and one of the awes doesn't line up, you will **transpose** (rather than reshape) one of the tensors to satisify the matrix multiplication rules.

### Changing the datatype of a tensor

In [ ]:
# Create a new tensor with default datatype (float32)
B = tf.constant([[1.7], [7.4]])
B, B.dtype

(<tf.Tensor: shape=(2, 1), dtype=float32, numpy=
 array([[1.7],
        [7.4]], dtype=float32)>,
 tf.float32)

In [ ]:
# int32
C = tf.constant([7, 10])
C

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# Change from float32 to float16 (reduced precision)
D = tf.cast(B, dtype=tf.float16)
D, D.dtype

(<tf.Tensor: shape=(2, 1), dtype=float16, numpy=
 array([[1.7],
        [7.4]], dtype=float16)>,
 tf.float16)

In [ ]:
# Change from int32 to float32
E = tf.cast(C, dtype = tf.float32)
E, E.dtype

(<tf.Tensor: shape=(2,), dtype=float32, numpy=array([ 7., 10.], dtype=float32)>,
 tf.float32)

In [ ]:
E_float16 = tf.cast(E, dtype= tf.float16)
E_float16

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

### Aggregating tensors
Aggregating tensors = condensing them from multiple values down to a smaller amount of values.

In [ ]:
# Get the absolute values
D = tf.constant([-7, -10])

tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Let's go through the following forms of aggregation:
* Get the minimum
* Get the maximum
* Get the mean of a tensor
* Get the sum of a tensor

In [ ]:
# Create a random tensor with values between 0 and 100 of size 50
rng = tf.random.Generator.from_seed(42)
D_ran = rng.uniform([5, 10], minval = 0, maxval = 101, dtype=tf.int32)
D_ran

<tf.Tensor: shape=(5, 10), dtype=int32, numpy=
array([[91,  2, 58, 62, 22,  3,  2, 71, 92, 28],
       [99, 75, 33, 44, 95, 86, 24, 38, 42, 25],
       [66, 29, 93, 46, 53, 94, 13, 45, 19,  5],
       [30, 97, 64, 99, 94, 32, 45, 40, 11,  8],
       [14, 51, 29, 55, 24, 26,  6, 22, 32, 29]], dtype=int32)>

In [ ]:
# Or we can try:
D = tf.constant(np.random.randint(0, 100, size=50))
D

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([63,  3, 77, 42, 44, 81, 77, 11, 95, 42, 75, 28, 68, 70, 87, 93, 27,
       67, 11, 90, 96, 22, 59, 47, 42, 56, 60, 31, 76, 89, 45, 81, 35, 29,
       49, 18, 35, 22, 17, 27, 38, 63, 68, 86, 30, 48,  2, 82, 79, 11])>

In [ ]:
# Get the min of a tensor
tf.reduce_min(D)

<tf.Tensor: shape=(), dtype=int64, numpy=2>

In [ ]:
# Get the max of a tensor
tf.reduce_max(D)

<tf.Tensor: shape=(), dtype=int64, numpy=96>

In [ ]:
# Get the mean of a tensor
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int64, numpy=51>

In [ ]:
# Get the sum of a tensor
tf.reduce_sum(D)

<tf.Tensor: shape=(), dtype=int64, numpy=2594>

**Exercise** With what we've just learned, find the variance and standard deviation of our `D` tensor using TensorFlow methods.

In [ ]:
# Variance
D_float = tf.cast(D, tf.float32)
var = tf.math.reduce_variance(D_float)
var

<tf.Tensor: shape=(), dtype=float32, numpy=727.9856>

In order to find variance, standard deviation and other statistical measures, we can also import the TensorFlow Probability library. Using the methods into the tfp module

In [ ]:
import tensorflow_probability as tfp
tfp.stats.variance(D_float), var
# We got the same results from these two methods

(<tf.Tensor: shape=(), dtype=float32, numpy=727.9856>,
 <tf.Tensor: shape=(), dtype=float32, numpy=727.9856>)

In [ ]:
# Standard deviation
stddev = tf.math.reduce_std(D_float)
stddev

<tf.Tensor: shape=(), dtype=float32, numpy=26.981209>

### Find the positional maximum and minimum

In [ ]:
# Create a new tensor for finding positional minimum and maxmimum
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# Find the positional maximum
tf.argmax(F) # Returns the "index" with the largest value across axes of a tensor.

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# Index on our largest value position
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Find the max value of F
tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# Check for equality
F[tf.argmax(F)] == tf.reduce_max(F)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [ ]:
# Find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# Find the minimum using the positional minimum index
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### Squeezing a tensor (removing all single dimensions)

In [ ]:
# Create a tensor to get started
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape = [50]), shape = (1,1,1,1,1,50))
G


<tf.Tensor: shape=(1, 1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255,
            0.03366041, 0.68467236, 0.74011743, 0.8724445 ,
            0.22632635, 0.22319686, 0.3103881 , 0.7223358 ,
            0.13318717, 0.5480639 , 0.5746088 , 0.8996835 ,
            0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
            0.72942245, 0.54583454, 0.10756552, 0.6767061 ,
            0.6602763 , 0.33695042, 0.60141766, 0.21062577,
            0.8527372 , 0.44062173, 0.9485276 , 0.23752594,
            0.81179297, 0.5263394 , 0.494308  , 0.21612847,
            0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
            0.23764038, 0.7817228 , 0.9671384 , 0.06870162,
            0.79873943, 0.66028714, 0.5871513 , 0.16461694,
            0.7381023 , 0.32054043]]]]]], dtype=float32)>

In [ ]:
# Squeeze all single dimensions
tf.squeeze(G)

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding tensors

In [ ]:
# Create a list of indices
some_list = [0, 1, 2, 3] # could be red, green, blue, purple
tf.one_hot(some_list, 4) # number of depth = number of columns

"""
tf.one_hot(
    indices,
    depth,
    on_value=None,
    off_value=None,
    axis=None,
    dtype=None,
    name=None
)
"""

'\ntf.one_hot(\n    indices,\n    depth,\n    on_value=None,\n    off_value=None,\n    axis=None,\n    dtype=None,\n    name=None\n)\n'

In [ ]:
color_list = ["red", "blue", "green"]
color_to_index = {"red": 0, "blue": 1, "green": 2}
color_indices = [color_to_index[color] for color in color_list]
tf.one_hot(color_indices, 3)

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [ ]:
# Specify custom values for one hot encoding
tf.one_hot(some_list, 4, on_value = "I love deep learning", off_value="I am an AI engineer!")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'I love deep learning', b'I am an AI engineer!',
        b'I am an AI engineer!', b'I am an AI engineer!'],
       [b'I am an AI engineer!', b'I love deep learning',
        b'I am an AI engineer!', b'I am an AI engineer!'],
       [b'I am an AI engineer!', b'I am an AI engineer!',
        b'I love deep learning', b'I am an AI engineer!'],
       [b'I am an AI engineer!', b'I am an AI engineer!',
        b'I am an AI engineer!', b'I love deep learning']], dtype=object)>

### Squaring, log, square root

In [ ]:
# Create a new tensor
H = tf.range(1,10)
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# Find the square root (Will error method requires non-int type)
tf.sqrt(tf.cast(H, dtype = tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.2360678, 2.4494896,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
#Find the log now
tf.math.log(tf.cast(H, dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

In [ ]:
# Round the values of a tensor to the nearest integer
tf.round(tf.sqrt(tf.cast(H, dtype = tf.float32)))

<tf.Tensor: shape=(9,), dtype=float32, numpy=array([1., 1., 2., 2., 2., 2., 3., 3., 3.], dtype=float32)>

# Tensor and NumPy
TensorFlow interacts beautifully with NumPy arrays.

***Note:*** One ofthe main differences between a TensorFlow tensor and a NumPy array is that a TensorFlow tensor can be run on a GPU or TPU (for faster numerical processing)

In [ ]:
# Create a tensor directly from a NumPy array
J = tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# Convert our tensor back to a NumPy array
np.array(J), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# Convert tensor J to a NumPy array
J.numpy(), type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
J = tf.constant([3.])
J.numpy()[0]

3.0

In [ ]:
# The default types of each are slightly different
numpy_J = tf.constant([np.array([3., 7.,10.])])
tensor_J = tf.constant([3., 7., 10.])
# Check the datatypes of each
numpy_J.dtype, tensor_J.dtype # We got different dtypes

(tf.float64, tf.float32)

### FInd access to GPUs

In [ ]:
# We can use this method to check what type of device our tensorFLow is running on
tf.config.list_physical_devices(), tf.config.list_physical_devices("GPU")

([PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU'),
  PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')],
 [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')])

In [ ]:
!nvidia-smi

Thu Feb 29 07:05:53 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   73C    P0              32W /  70W |    629MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

> **Note:** If you have access to a CUDA-enabled GPU, TensorFlow will automatically use it whenever possible

***Exercise***
* Read through the list of TensorFlow Python APIs, pick one we haven't gone through in this notebook, reverse engineer it (write out the documentation code for yourself) and figure out what it does.

* Try to create a series of tensor functions to calculate your most recent grocery bill (it's okay if you don't use the names of the items, just the price in numerical form).
How would you calculate your grocery bill for the month and for the year using tensors?

* Go through the TensorFlow 2.x quick start for beginners tutorial (be sure to type out all of the code yourself, even if you don't understand it).
Are there any functions we used in here that match what's used in there? Which are the same? Which haven't you seen before?

* Watch the video "What's a tensor?" - a great visual introduction to many of the concepts we've covered in this notebook.

In [ ]:
# Exercise 1
# tf.sigmoid()
x = tf.constant([0.0, 1.0, 50.0, 100.0])
tf.math.sigmoid(x)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.5       , 0.73105854, 1.        , 1.        ], dtype=float32)>

In [ ]:
# Exercise 2
grocery_month = tf.constant(np.random.randint(100, size = (4, 7)))
grocery_year = tf.constant(np.random.randint(100, size = (365)))
grocery_month, grocery_year

(<tf.Tensor: shape=(4, 7), dtype=int64, numpy=
 array([[75, 64, 94, 38, 70, 20, 32],
        [36, 50, 35, 48,  1, 85, 11],
        [42, 97, 70, 17, 91, 69, 88],
        [90, 72, 28, 17,  8, 41, 48]])>,
 <tf.Tensor: shape=(365,), dtype=int64, numpy=
 array([25,  0, 11, 61, 57, 31, 68, 77, 93, 59, 81, 70, 60, 90, 60, 45, 91,
        72, 85, 28,  0, 91, 89, 19,  0, 44, 14, 95, 27,  7, 26, 29, 97, 67,
        93, 72, 67, 81, 91, 81,  4, 46, 33, 34, 45, 18, 74,  1, 91, 17, 61,
        81, 11, 22, 89, 81, 27, 51, 44, 42, 96, 71, 41, 48, 18, 32, 69, 12,
        76, 19, 97, 39, 66, 49, 48, 14, 68, 86,  0, 57, 17, 31, 95, 63,  9,
        69,  6, 55, 97,  4, 44, 63,  6,  4, 67, 19,  4, 45, 85, 69, 46, 82,
        79, 30, 93, 75, 59, 30, 86, 96, 80, 50,  7, 48, 17, 31, 41, 76, 46,
        11, 43, 21, 29,  7, 14, 62, 79, 35, 74, 63, 11, 50, 74, 79, 83, 71,
        23, 68, 15, 78, 70, 77, 20, 91,  8,  3, 12, 80, 28, 42, 93, 95, 38,
        40, 66, 12, 45, 33, 44, 51, 80, 37, 26, 67,  6, 84, 50, 68,

In [ ]:
print(f"Grocery bill for the month: ${tf.reduce_sum(grocery_month)}")
print(f"Grocery bill for the year: ${tf.reduce_sum(grocery_year)}")

Grocery bill for the month: $1437
Grocery bill for the year: $18509


In [ ]:
# Exercise 3
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/ 255.0, x_test / 255.0

>`Sequential` is useful for stacking layers where each layer has one input tensor and one output tensor. Layers are functions with a known mathematical structure that can be reused and have trainable variables. Most TensorFlow models are composed of layers. This model uses the `Flatten`, `Dense`, and `Dropout` layers.

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128, activation="relu"),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
predictions = model(x_train[:1]).numpy()
predictions

array([[ 0.5184995 , -0.08127002, -0.6679361 , -0.07098393, -0.4133709 ,
        -0.31492865, -0.14305757,  0.5422055 , -0.54183435,  0.48760945]],
      dtype=float32)

In [ ]:
# The tf.nn.softmax function converts these logits to probabilities for each class:
tf.nn.softmax(predictions).numpy()

array([[0.16411762, 0.09009042, 0.05010635, 0.09102188, 0.06463221,
        0.07131846, 0.08469243, 0.16805467, 0.05684052, 0.1591255 ]],
      dtype=float32)

In [ ]:
# Define a loss function for training using losses.SparseCategoricalCrossentropy:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

> The loss function takes a vector of ground truth values and a vector of logits and returns a scalar loss for each example. This loss is equal to the negative log probability of the true class: The loss is zero if the model is sure of the correct class.

>This untrained model gives probabilities close to random (1/10 for each class), so the initial loss should be close to -tf.math.log(1/10) ~= 2.3

In [ ]:
loss_fn(y_train[:1], predictions).numpy()

2.6406002

> Before you start training, configure and compile the model using Keras `Model.compile`. Set the `optimizer` class to `adam`, set the `loss` to the `loss_fn` function you defined earlier, and specify a metric to be evaluated for the model by setting the `metrics` parameter to `accuracy`.

In [ ]:
model.compile(optimizer = "adam",
              loss = loss_fn,
              metrics = ["accuracy"])

### Train and evaluate your model
> use the `Model.fit` meghod to adjust your model parameters and minimize the loss:

In [ ]:
model.fit(x_train, y_train, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 9s 3ms/step - loss: 0.2996 - accuracy: 0.9134
Epoch 2/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1467 - accuracy: 0.9565
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.1113 - accuracy: 0.9660
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0883 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0763 - accuracy: 0.9755


>The `Model.evaluate` method checks the model's performance, usually on a validation set or test set.

In [ ]:
model.evaluate(x_test, y_test, verbose=2)

313/313 - 1s - loss: 0.0728 - accuracy: 0.9771 - 1s/epoch - 3ms/step


[0.07283931225538254, 0.9771000146865845]

> The image classifier is now trained to ~98% accuracy on this dataset. To learn more, read the [TensorFlow tutorials.](https://www.tensorflow.org/tutorials/)

>If you want your model to return a probability, you can wrap the trained model, and attach the softmax to it:

In [ ]:
probability_model = tf.keras.Sequential([
    model,
    tf.keras.layers.Softmax()
])

In [ ]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[8.63417338e-09, 1.10842562e-08, 5.32629492e-05, 1.54178648e-04,
        1.34052821e-11, 1.53676353e-07, 1.56971170e-13, 9.99787748e-01,
        6.41674035e-07, 3.99917326e-06],
       [3.75887405e-10, 8.12806611e-05, 9.99877095e-01, 4.14237365e-05,
        3.67684138e-16, 5.65797187e-08, 2.16881766e-08, 8.88289415e-14,
        1.77092438e-08, 7.84495658e-15],
       [6.43635133e-07, 9.96783853e-01, 7.31925538e-05, 1.20602035e-05,
        1.13010892e-05, 8.85018198e-06, 5.04085438e-06, 2.94907345e-03,
        1.55333619e-04, 7.94842435e-07],
       [9.98918414e-01, 1.43333709e-08, 9.72511538e-04, 7.16080024e-07,
        4.62719534e-08, 2.11493279e-05, 2.97716233e-05, 1.71741740e-05,
        2.88273156e-07, 3.99031342e-05],
       [9.11576763e-07, 1.01229233e-07, 7.46781416e-06, 2.80724748e-07,
        9.75839257e-01, 4.34857839e-06, 5.82820485e-06, 1.32073528e-05,
        2.79197434e-06, 2.41258480e-02]], dtype=float32)>